apiVersion: skaffold/v4beta2
kind: Config
build:
   artifacts:
      - image: chinaemerem/ticketing-auth
        context: auth
        sync:
           manual:
              - src: src/**/*.ts
                dest: .
        docker:
           dockerfile: Dockerfile
      - image: chinaemerem/tickets
        context: tickets
        sync:
           manual:
              - src: src/**/*.ts
                dest: .
        docker:
           dockerfile: Dockerfile
      - image: chinaemerem/orders
        context: orders
        sync:
           manual:
              - src: src/**/*.ts
                dest: .
        docker:
           dockerfile: Dockerfile
      - image: chinaemerem/expiration
        context: expiration
        sync:
           manual:
              - src: src/**/*.ts
                dest: .
        docker:
           dockerfile: Dockerfile
      - image: chinaemerem/payments
        context: payments
        sync:
           manual:
              - src: src/**/*.ts
                dest: .
        docker:
           dockerfile: Dockerfile
      - image: chinaemerem/client
        context: client
        sync:
           manual:
              - src: "**/*.ts"
                dest: .
        docker:
           dockerfile: Dockerfile
   local:
      push: false
manifests:
   rawYaml:
      - ./infra/k8s/*
deploy:
   kubectl: {}
