import Head from "next/head"
import buildClient from "../api/build-client"
import Link from "next/link"

const Home = ({ currentUser, tickets }: { currentUser: any; tickets: any }) => {
	const ticketList = tickets.map((ticket: any) => {
		return (
			<tr key={ticket.id}>
				<td>{ticket.price}</td>
				<td>{ticket.title}</td>
				<td>
					<Link
						href={`/ticket/[ticketId]`}
						as={`/ticket/${ticket.id}`}
						className='nav-link'
					>
						View
					</Link>
				</td>
			</tr>
		)
	})
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link
					rel='icon'
					href='/favicon.ico'
				/>
			</Head>
			<main>
				<div>
					<h1>Tickets</h1>

					<table className='table'>
						<thead>
							<tr>
								<th>Title</th>
								<th>price</th>
								<th>Link</th>
							</tr>
						</thead>
						<tbody>{ticketList}</tbody>
					</table>
				</div>
			</main>
		</>
	)
}

Home.getInitialProps = async (ctx: any) => {
	const { data } = await buildClient(ctx).get("/api/tickets")
	return { tickets: data }
}

export default Home
