import Head from "next/head"
import { NextPage } from "next"
import axios, { AxiosResponse } from "axios"
import buildClient from "../api/build-client"
interface IProps {
	currentUser: any
}
const Home: NextPage<IProps> = ({ currentUser }) => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link
					rel='icon'
					href='/favicon.ico'
				/>
			</Head>
			<main>
				{currentUser ? (
					<h1>you are signed in</h1>
				) : (
					<h1>you are not signed in</h1>
				)}
			</main>
		</>
	)
}

Home.getInitialProps = async ctx => {
	const { data } = await buildClient(ctx).get("/api/users/currentuser")
	return data
}

export default Home
